site_name: Blue Morpho Docs
site_url: https://getbluemorpho.github.io/blue-morpho/
theme:
  name: material
  font:
    text: DM Sans
    code: DM Sans
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.path
    - navigation.sections

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# extra_css:
  # - stylesheets/extra.css      

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

copyright: ⓒ Copyright 2025 - Blue Morpho